### ISSUE TITLE
'bx' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by mrotheram** [dtoczala/IBM_Cloud_Admin#5]
Hi,

Fairly new to python so this may be user error however I have followed the instructions and installed the 2 packages (it needed both unicodecsv and pandas) but now I get the following output error when running the script. Any ideas?

> C:\IBM_Cloud_Admin-master>python IBM_Cloud_Admin.py -t apiKey.json
> 'bx' is not recognized as an internal or external command,
> operable program or batch file.
> Traceback (most recent call last):
>   File "IBM_Cloud_Admin.py", line 2600, in <module>
>     stat = IBMCloudLogin(cloudUser,cloudPwd,cloudToken,API_ENDPOINTS['us-south'])
>   File "IBM_Cloud_Admin.py", line 580, in IBMCloudLogin
>     (version,major,minor) = parseBxVersion(errout)
>   File "IBM_Cloud_Admin.py", line 551, in parseBxVersion
>     metaVersion = re.search(r'version\s*([\d.]+)',bxVersion).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dtoczala** [comment]
You need to install the IBM Cloud command line interface (CLI).
Go to the [Docs page](https://console.bluemix.net/docs/cli/index.html#overview) on  IBM Cloud to download and install the CLI.

**Comment by mrotheram** [comment]
Installed IBM CLI and logged into my region and account. Re ran the script and this time I get the following

> C:\IBM_Cloud_Admin-master>python IBM_Cloud_Admin.py -t apiKey.json
> Traceback (most recent call last):
>   File "IBM_Cloud_Admin.py", line 2600, in <module>
>     stat = IBMCloudLogin(cloudUser,cloudPwd,cloudToken,API_ENDPOINTS['us-south'])
>   File "IBM_Cloud_Admin.py", line 580, in IBMCloudLogin
>     (version,major,minor) = parseBxVersion(errout)
>   File "IBM_Cloud_Admin.py", line 551, in parseBxVersion
>     metaVersion = re.search(r'version\s*([\d.]+)',bxVersion).group(1)
>   File "C:\Users\mroth\AppData\Local\Programs\Python\Python36\lib\re.py", line 182, in search
>     return _compile(pattern, flags).search(string)
> TypeError: cannot use a string pattern on a bytes-like object

**Comment by dtoczala** [comment]
I have someone else having this same issue.  I hope to get some time to dig into this over the next week or so.

**Comment by dtoczala** [comment]
OK - so now I am including instructions on how to install Anaconda so people can pull down the right Python packages, and so I don't have these dependency and environment problems with other people using this.  Close this issue.
